//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMP.Models.Oracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWS_BASE_INFO
    {
        public string STN { get; set; }
        public string SNAME { get; set; }
        public Nullable<decimal> LAT { get; set; }
        public Nullable<decimal> LON_ { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> STNTYPE { get; set; }
        public Nullable<decimal> QXTYPE { get; set; }
        public string BNORMAL { get; set; }
        public string QXNAME { get; set; }
    }
}
