//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMP.Models.Oracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class YTHPT_EMERGENCY_SERVICE
    {
        public string FID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
    }
}
