//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMP.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficialAccounts
    {
        public OfficialAccounts()
        {
            this.AutoStations = new HashSet<AutoStations>();
            this.Messages = new HashSet<Messages>();
            this.ServiceInfos_Categorys = new HashSet<ServiceInfos_Categorys>();
            this.ServiceInfos = new HashSet<ServiceInfos>();
            this.ShortNearInfos = new HashSet<ShortNearInfos>();
            this.Subscribers = new HashSet<Subscribers>();
            this.Users = new HashSet<Users>();
            this.WarnInfos = new HashSet<WarnInfos>();
            this.WeatherInfos_Categorys = new HashSet<WeatherInfos_Categorys>();
            this.WeatherInfos = new HashSet<WeatherInfos>();
        }
    
        public System.Guid AccountID { get; set; }
        public string WeiXinName { get; set; }
        public string OriginalID { get; set; }
        public string WeiXinNumber { get; set; }
        public string AppID { get; set; }
        public string AppSecret { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string WebSiteTitle { get; set; }
        public string CountryName { get; set; }
        public string CountryFullName { get; set; }
        public string WarnReleaseTemplateID { get; set; }
        public string WarnRelieveTemplateID { get; set; }
        public string CompanyName { get; set; }
        public string SanTianImg { get; set; }
        public string ShortNearImg { get; set; }
        public string SubscribeLink { get; set; }
    
        public virtual ICollection<AutoStations> AutoStations { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<ServiceInfos_Categorys> ServiceInfos_Categorys { get; set; }
        public virtual ICollection<ServiceInfos> ServiceInfos { get; set; }
        public virtual ICollection<ShortNearInfos> ShortNearInfos { get; set; }
        public virtual ICollection<Subscribers> Subscribers { get; set; }
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<WarnInfos> WarnInfos { get; set; }
        public virtual ICollection<WeatherInfos_Categorys> WeatherInfos_Categorys { get; set; }
        public virtual ICollection<WeatherInfos> WeatherInfos { get; set; }
    }
}
