//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMP.Models.SQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QMPEntities : DbContext
    {
        public QMPEntities()
            : base("name=QMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AutoStations> AutoStations { get; set; }
        public DbSet<Messages> Messages { get; set; }
        public DbSet<Messages_Categorys> Messages_Categorys { get; set; }
        public DbSet<OfficialAccounts> OfficialAccounts { get; set; }
        public DbSet<ServiceInfos> ServiceInfos { get; set; }
        public DbSet<ServiceInfos_Categorys> ServiceInfos_Categorys { get; set; }
        public DbSet<ServiceInfos_Images> ServiceInfos_Images { get; set; }
        public DbSet<ShortNearInfos> ShortNearInfos { get; set; }
        public DbSet<Subscribers> Subscribers { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Users_Roles> Users_Roles { get; set; }
        public DbSet<WarnInfos> WarnInfos { get; set; }
        public DbSet<WarnInfos_Categorys> WarnInfos_Categorys { get; set; }
        public DbSet<WeatherInfos> WeatherInfos { get; set; }
        public DbSet<WeatherInfos_Categorys> WeatherInfos_Categorys { get; set; }
    }
}
