//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMP.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Messages = new HashSet<Messages>();
            this.ServiceInfos = new HashSet<ServiceInfos>();
            this.ShortNearInfos = new HashSet<ShortNearInfos>();
            this.WarnInfos = new HashSet<WarnInfos>();
            this.WeatherInfos = new HashSet<WeatherInfos>();
        }
    
        public System.Guid UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<System.Guid> RoleID { get; set; }
        public Nullable<System.Guid> AccountID { get; set; }
    
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual OfficialAccounts OfficialAccounts { get; set; }
        public virtual ICollection<ServiceInfos> ServiceInfos { get; set; }
        public virtual ICollection<ShortNearInfos> ShortNearInfos { get; set; }
        public virtual Users_Roles Users_Roles { get; set; }
        public virtual ICollection<WarnInfos> WarnInfos { get; set; }
        public virtual ICollection<WeatherInfos> WeatherInfos { get; set; }
    }
}
